# Generated by Django 2.2.13 on 2020-06-24 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fruit_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commodity_data',
            unique_together={('country', 'commodity')},
        ),
    ]
