# Generated by Django 2.2.13 on 2020-06-25 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit_app', '0003_auto_20200624_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity_data',
            name='fixed_overhead',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='commodity_data',
            name='variable_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
