# Generated by Django 2.2.13 on 2020-07-01 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit_app', '0006_auto_20200701_0109'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='commodity_data',
            name='country_2_letter_code',
        ),
        migrations.RemoveConstraint(
            model_name='country',
            name='country_2_letter_code',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='country',
            new_name='country_code',
        ),
        migrations.AddConstraint(
            model_name='country',
            constraint=models.CheckConstraint(check=models.Q(country_code__regex='^[a-zA-Z]{2,2}'), name='country_2_letter_code'),
        ),
    ]
