# Generated by Django 2.2.13 on 2020-07-11 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fruit_app', '0009_auto_20200701_0626'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commodity_Data',
            new_name='CommodityData',
        ),
    ]
